#!/usr/bin/env python3
import os
import sys

from _common import log_event, private_env, root

args = sys.argv[1:]
log_event("tmux", args)
real_tmux = (root() / "state" / "real-tmux").read_text(encoding="utf-8")
environment = private_env()
environment.pop("TMUX", None)
if args in (["--version"], ["-V"]):
    os.execve(real_tmux, [real_tmux, "-V"], environment)
socket = str(root() / "prism-tmux" / "tmux.sock")
os.execve(real_tmux, [real_tmux, "-S", socket, *args], environment)
