# Prism Workflow Definition schema v2
schema_version = 2
id = "your.package/workflow"
name = "workflow"
description = ""
launch = ["manual"]

[[steps]]
id = "first"
class = "action"
use = "prism.standard/echo"
skippable = false
