insert into auto_run (
  id, harness_id, repo_root, worktree_path, worktree_incarnation, branch, mode,
  implementation_source, plan_path, plan_run_mode, variant, agent_profile,
  prompt_summary, initial_prompt, status, pause_requested, selected_step_run_id,
  pr_number, pr_url, current_head_sha, review_baseline_json, stabilization_status,
  stabilization_blocker, stabilization_next_work, pending_push_json,
  created_unix_ms, updated_unix_ms, archived_unix_ms, adapter_id
) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(id) do update set
  repo_root = excluded.repo_root,
  harness_id = excluded.harness_id,
  adapter_id = excluded.adapter_id,
  worktree_path = excluded.worktree_path,
  worktree_incarnation = excluded.worktree_incarnation,
  branch = excluded.branch,
  mode = excluded.mode,
  implementation_source = excluded.implementation_source,
  plan_path = excluded.plan_path,
  plan_run_mode = excluded.plan_run_mode,
  variant = excluded.variant,
  agent_profile = excluded.agent_profile,
  prompt_summary = excluded.prompt_summary,
  initial_prompt = excluded.initial_prompt,
  status = excluded.status,
  pause_requested = excluded.pause_requested,
  selected_step_run_id = excluded.selected_step_run_id,
  pr_number = excluded.pr_number,
  pr_url = excluded.pr_url,
  current_head_sha = excluded.current_head_sha,
  review_baseline_json = excluded.review_baseline_json,
  stabilization_status = excluded.stabilization_status,
  stabilization_blocker = excluded.stabilization_blocker,
  stabilization_next_work = excluded.stabilization_next_work,
  pending_push_json = excluded.pending_push_json,
  updated_unix_ms = excluded.updated_unix_ms,
  archived_unix_ms = excluded.archived_unix_ms
where auto_run.status != 'aborted' or excluded.status = 'queued'
